# Generated by Django 3.0.2 on 2020-01-30 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=56)),
                ('ChargeCode', models.CharField(max_length=16)),
                ('PaysVAT', models.BooleanField()),
                ('AllowedChemicals', models.BooleanField()),
                ('Enabled', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=50)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=3)),
                ('Quantity', models.PositiveIntegerField()),
                ('WarningQuantity', models.PositiveIntegerField()),
                ('IsChemical', models.BooleanField()),
                ('PackSize', models.PositiveSmallIntegerField()),
                ('ForSale', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateTimeField()),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=56)),
                ('LoginCode', models.CharField(max_length=16)),
                ('AccessLevel', models.CharField(choices=[('TR', 'Trainee'), ('BA', 'Basic'), ('MA', 'Manager')], default='TR', max_length=2)),
                ('Enabled', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='StockCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateTimeField()),
                ('StaffID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='StockCheckItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ObservedQuantity', models.PositiveIntegerField()),
                ('ExpectedQuantity', models.PositiveIntegerField()),
                ('ItemID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Item')),
                ('StockCheckID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.StockCheck')),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.PositiveIntegerField()),
                ('ReturnedQuantity', models.PositiveIntegerField()),
                ('ItemID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Item')),
                ('SaleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Sale')),
            ],
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateTimeField()),
                ('Reason', models.CharField(choices=[('DA', 'Damaged'), ('NN', 'Not Needed'), ('WI', 'Wrong Item')], max_length=2)),
                ('Quantity', models.PositiveIntegerField()),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Customer')),
                ('SaleItemID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.SaleItem')),
                ('StaffID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateTimeField()),
                ('Status', models.CharField(choices=[('TO', 'To Order'), ('ON', 'On Order'), ('CA', 'Cancelled'), ('CO', 'Completed')], default='TO', max_length=2)),
                ('ItemID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Item')),
                ('StaffID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=56)),
                ('HeadID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='DepartmentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Department'),
        ),
    ]
