# Generated by Django 3.0.2 on 2020-01-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Price',
            field=models.PositiveIntegerField(),
        ),
    ]
