# Generated by Django 3.0.2 on 2020-01-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200130_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
