# Generated by Django 3.0.2 on 2020-02-04 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200204_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='department_id',
            new_name='dept',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='head_id',
            new_name='head',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='staff_id',
            new_name='staff',
        ),
        migrations.RenameField(
            model_name='return',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='return',
            old_name='sale_item_id',
            new_name='sale_item',
        ),
        migrations.RenameField(
            model_name='return',
            old_name='staff_id',
            new_name='staff',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='saleitem',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='saleitem',
            old_name='sale_id',
            new_name='sale',
        ),
        migrations.RenameField(
            model_name='stockcheck',
            old_name='staff_id',
            new_name='staff',
        ),
        migrations.RenameField(
            model_name='stockcheckitem',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='stockcheckitem',
            old_name='stock_check_id',
            new_name='stock_check',
        ),
    ]
