# Generated by Django 3.0.2 on 2020-01-30 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200130_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='ForSale',
            new_name='for_sale',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='IsChemical',
            new_name='is_chemical',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='PackSize',
            new_name='pack_size',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Quantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='WarningQuantity',
            new_name='warning_quantity',
        ),
    ]
