# Generated by Django 3.0.2 on 2020-02-05 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200205_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='access_level',
            new_name='notification_type',
        ),
    ]
