# Generated by Django 3.0.2 on 2020-02-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200205_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(default='examplelink', max_length=300),
            preserve_default=False,
        ),
    ]
