# Generated by Django 3.0.2 on 2020-02-05 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_notification_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='message',
            new_name='text',
        ),
    ]
