# Generated by Django 3.0.2 on 2020-02-05 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_notification_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
            preserve_default=False,
        ),
    ]
